version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: goparty_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 230613
      MYSQL_DATABASE: goparty
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
